pipeline {
    agent { label 'master' }   ///agent { label 'docker' }
    triggers {
        githubPush()
    }
    environment {
        // Specify your environment variables.
        APP_VERSION = '1'
    }
    stages {
    
   
    stage('Code Quality Check via SonarQube') {
        steps {
        script {
        def scannerHome = tool 'sonarscanner';
            withSonarQubeEnv("sonarqube") {
            sh "${tool("sonarscanner")}/bin/sonar-scanner \
            -Dsonar.projectKey=kubernetes-appmodernization \
            -Dsonar.sources=. \
            -Dsonar.css.node=. \
            -Dsonar.host.url=http://10.10.121.29:9000 \
            -Dsonar.login=0c23ed05dcf333d0d74e956383d912e5d4f906e8"
               }
           }
       }
    }

    stage('Code Security Scanner') {
        steps {
              sh 'sudo chmod 777 -R /var/lib/jenkins/workspace/AM_Workflow_UAT_Service/'
              sh 'trivy fs /var/lib/jenkins/workspace/AM_Workflow_UAT_Service/'
                
        }
    }

    stage('Build-workflow service') {
        steps {
              // Print all the environment variables.
              sh 'printenv'
              sh 'echo $GIT_BRANCH'
              sh 'echo $GIT_COMMIT'
               
              sh 'sudo chmod 777 -R /var/lib/jenkins/workspace/AM_Workflow_UAT_Service'
              //sh 'mkdir /var/lib/jenkins/workspace/AM_Workflow_UAT_Service/backend/workflow_service/rootpackage'
              sh 'cp /var/lib/jenkins/workspace/AM_Workflow_UAT_Service/package.json /var/lib/jenkins/workspace/AM_Workflow_UAT_Service/backend/workflow_service/rootpackage'
              sh 'sudo docker build --network=host -t workflow-uat:"$BUILD_NUMBER" /var/lib/jenkins/workspace/AM_Workflow_UAT_Service/backend/workflow_service'
              
              }
    }

    stage('Artifact to Nexus-workflow service') {
        steps {
              echo 'Uploading docker image to nexus server'
              sh 'sudo docker tag workflow-uat:"$BUILD_NUMBER" 10.10.121.29:8085/workflow-uat:"$BUILD_NUMBER" '
              sh 'sudo docker push 10.10.121.29:8085/workflow-uat:"$BUILD_NUMBER" '
              sh 'sudo docker rmi -f workflow-uat:"$BUILD_NUMBER" '
              }
    }
               
    stage('Test') {
        steps {
                echo 'PHP Unit tests'
               
              }
    }

    stage('deployment-workflow service') {
            
        steps {
                echo 'Deploying helm chart '
                sh 'sudo helm upgrade --install workflow /var/lib/jenkins/workspace/AM_Workflow_UAT_Service/backend/workflow_service/helm_workflow-service/ --set image=10.10.121.29:8085/workflow-uat:"$BUILD_NUMBER" -n appmodernization'
              }
    }
    }
    post {
        always {
        
        
         script {
                if (currentBuild.currentResult == 'FAILURE') {
                    emailext subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - FAILED!!!',
                        body: '$DEFAULT_CONTENT',
                        recipientProviders: [
                            [$class: 'RequesterRecipientProvider']
                        ], 
                        replyTo: '$DEFAULT_REPLYTO',
                        to: 'prakash.mekapothula@cloud4c.com,satyanarayana.reddy@cloud4c.com,santosh.kalingwar@cloud4c.com,srija.yalala@cloud4c.com '
                        
                }
            }
            /*
            script {
                if (currentBuild.currentResult == 'SUCCESS') {
                   echo 'Running ADMIN-CENTER Selenium Testcases pipeline!'
                   build job: 'Selenium/OPF-ADMIN-functional-automation-scripts/', wait: false
                }
        }
        */

              updateGitlabCommitStatus(name: 'Jenkins', state: 'success')
              }
    }

  
}
