pipeline {
    agent { label 'master' }   ///agent { label 'docker' }
    triggers {
        githubPush()
    }
    environment {
        // Specify your environment variables.
        APP_VERSION = '1'
    }
    stages {
    
   
    stage('Code Quality Check via SonarQube') {
        steps {
        script {
        def scannerHome = tool 'sonarscanner';
            withSonarQubeEnv("sonarqube") {
            sh "${tool("sonarscanner")}/bin/sonar-scanner \
            -Dsonar.projectKey=kubernetes-appmodernization \
            -Dsonar.sources=. \
            -Dsonar.css.node=. \
            -Dsonar.host.url=http://10.10.121.29:9000 \
            -Dsonar.login=0c23ed05dcf333d0d74e956383d912e5d4f906e8"
               }
           }
       }
    }

    stage('Code Security Scanner') {
            steps {
              sh 'sudo chmod 777 -R /var/lib/jenkins/workspace/appmodernization/'
              sh 'trivy fs /var/lib/jenkins/workspace/appmodernization/'
                
        }
    }
        stage('Build1') {
            steps {
                // Print all the environment variables.
                sh 'printenv'
                sh 'echo $GIT_BRANCH'
                sh 'echo $GIT_COMMIT'
               
                sh 'sudo chmod 777 -R /var/lib/jenkins/workspace/appmodernization'
               sh 'sudo docker build --network=host -t appmodernization-uat:"$BUILD_NUMBER" /var/lib/jenkins/workspace/appmodernization/frontend'
              
            }
        }

        stage('Build2') {
            steps {
                // Print all the environment variables.
                sh 'printenv'
                sh 'echo $GIT_BRANCH'
                sh 'echo $GIT_COMMIT'
               
                sh 'sudo chmod 777 -R /var/lib/jenkins/workspace/appmodernization'
               sh 'sudo docker build --network=host -t appmodernizationbackend-uat:"$BUILD_NUMBER" /var/lib/jenkins/workspace/appmodernization/backend'
              
            }
        }

        stage('Build kafka') {
            steps {
                // Print all the environment variables.
                sh 'printenv'
                sh 'echo $GIT_BRANCH'
                sh 'echo $GIT_COMMIT'
               
                sh 'sudo chmod 777 -R /var/lib/jenkins/workspace/appmodernization'
               sh 'sudo docker build --network=host -t kafka-uat:"$BUILD_NUMBER" /var/lib/jenkins/workspace/appmodernization/backend/kafka_service'
              
            }
        }

        stage('Build ticket') {
            steps {
                // Print all the environment variables.
                sh 'printenv'
                sh 'echo $GIT_BRANCH'
                sh 'echo $GIT_COMMIT'
               
                sh 'sudo chmod 777 -R /var/lib/jenkins/workspace/appmodernization'
               sh 'sudo docker build --network=host -t ticket-uat:"$BUILD_NUMBER" /var/lib/jenkins/workspace/appmodernization/backend/ticket_service'
              
            }
        }

        stage('Build gateway') {
            steps {
                // Print all the environment variables.
                sh 'printenv'
                sh 'echo $GIT_BRANCH'
                sh 'echo $GIT_COMMIT'
               
                sh 'sudo chmod 777 -R /var/lib/jenkins/workspace/appmodernization'
               sh 'sudo docker build --network=host -t gateway-uat:"$BUILD_NUMBER" /var/lib/jenkins/workspace/appmodernization/backend/gateway'
              
            }
        }

        stage('Build fileserver') {
            steps {
                // Print all the environment variables.
                sh 'printenv'
                sh 'echo $GIT_BRANCH'
                sh 'echo $GIT_COMMIT'
               
                sh 'sudo chmod 777 -R /var/lib/jenkins/workspace/appmodernization'
               sh 'sudo docker build --network=host -t fileserver-uat:"$BUILD_NUMBER" /var/lib/jenkins/workspace/appmodernization/backend/file_server_service'
              
            }
        }
        
        
        stage('Artifact To Nexus1') {
            steps {
                echo 'Uploading docker image to nexus server'
                sh 'sudo docker tag appmodernization-uat:"$BUILD_NUMBER" 10.10.121.29:8085/appmodernization-uat:"$BUILD_NUMBER" '
                sh 'sudo docker push 10.10.121.29:8085/appmodernization-uat:"$BUILD_NUMBER" '
                sh 'sudo docker rmi -f appmodernization-uat:"$BUILD_NUMBER" '
            }
        }

        stage('Artifact To Nexus2') {
            steps {
                echo 'Uploading docker image to nexus server'
                sh 'sudo docker tag appmodernizationbackend-uat:"$BUILD_NUMBER" 10.10.121.29:8085/appmodernizationbackend-uat:"$BUILD_NUMBER" '
                sh 'sudo docker push 10.10.121.29:8085/appmodernizationbackend-uat:"$BUILD_NUMBER" '
                sh 'sudo docker rmi -f appmodernizationbackend-uat:"$BUILD_NUMBER" '
            }
        }

        stage('Artifact To Nexus-kafka') {
            steps {
                echo 'Uploading docker image to nexus server'
                sh 'sudo docker tag kafka-uat:"$BUILD_NUMBER" 10.10.121.29:8085/kafka-uat:"$BUILD_NUMBER" '
                sh 'sudo docker push 10.10.121.29:8085/kafka-uat:"$BUILD_NUMBER" '
                sh 'sudo docker rmi -f kafka-uat:"$BUILD_NUMBER" '
            }
        }

        stage('Artifact To Nexus-ticket') {
            steps {
                echo 'Uploading docker image to nexus server'
                sh 'sudo docker tag ticket-uat:"$BUILD_NUMBER" 10.10.121.29:8085/ticket-uat:"$BUILD_NUMBER" '
                sh 'sudo docker push 10.10.121.29:8085/ticket-uat:"$BUILD_NUMBER" '
                sh 'sudo docker rmi -f ticket-uat:"$BUILD_NUMBER" '
            }
        }

        stage('Artifact To Nexus-gateway') {
            steps {
                echo 'Uploading docker image to nexus server'
                sh 'sudo docker tag gateway-uat:"$BUILD_NUMBER" 10.10.121.29:8085/gateway-uat:"$BUILD_NUMBER" '
                sh 'sudo docker push 10.10.121.29:8085/gateway-uat:"$BUILD_NUMBER" '
                sh 'sudo docker rmi -f gateway-uat:"$BUILD_NUMBER" '
            }
        }

        stage('Artifact To Nexus-fileserver') {
            steps {
                echo 'Uploading docker image to nexus server'
                sh 'sudo docker tag fileserver-uat:"$BUILD_NUMBER" 10.10.121.29:8085/fileserver-uat:"$BUILD_NUMBER" '
                sh 'sudo docker push 10.10.121.29:8085/fileserver-uat:"$BUILD_NUMBER" '
                sh 'sudo docker rmi -f fileserver-uat:"$BUILD_NUMBER" '
            }
        }
       
        
        stage('Test') {
            steps {
                echo 'PHP Unit tests'
               
            }
        }
        stage('deployment1') {
            
            steps {
                echo 'Deploying helm chart '
                sh 'sudo helm upgrade --install appmodernization /var/lib/jenkins/workspace/appmodernization/helm_appmodernization/ --set image=10.10.121.29:8085/appmodernization-uat:"$BUILD_NUMBER" -n appmodernization '
            }
        }
         stage('deployment2') {
            
            steps {
                echo 'Deploying helm chart '
                sh 'sudo helm upgrade --install appmodernizationbackend /var/lib/jenkins/workspace/appmodernization/helm_appmodernizationbackend/ --set image=10.10.121.29:8085/appmodernizationbackend-uat:"$BUILD_NUMBER" -n appmodernization '
            }
        }
         stage('deployment-kafka') {
            
            steps {
                echo 'Deploying helm chart '
                sh 'sudo helm upgrade --install kafka /var/lib/jenkins/workspace/appmodernization/helm_kafka-service/ --set image=10.10.121.29:8085/kafka-uat:"$BUILD_NUMBER" -n appmodernization '
            }
        }
        stage('deployment-ticket') {
            
            steps {
                echo 'Deploying helm chart '
                sh 'sudo helm upgrade --install ticket /var/lib/jenkins/workspace/appmodernization/helm_ticket-service/ --set image=10.10.121.29:8085/ticket-uat:"$BUILD_NUMBER" -n appmodernization '
            }
        }

        stage('deployment-gateway') {
            
            steps {
                echo 'Deploying helm chart '
                sh 'sudo helm upgrade --install gateway /var/lib/jenkins/workspace/appmodernization/helm_gateway/ --set image=10.10.121.29:8085/gateway-uat:"$BUILD_NUMBER" -n appmodernization '
            }
        }

        stage('deployment-fileserver') {
            
            steps {
                echo 'Deploying helm chart '
                sh 'sudo helm upgrade --install fileserver /var/lib/jenkins/workspace/appmodernization/helm_fileserver-service/ --set image=10.10.121.29:8085/fileserver-uat:"$BUILD_NUMBER" -n appmodernization '
            }
        }

    }
  post {
        always {
        
        
         script {
                if (currentBuild.currentResult == 'FAILURE') {
                    emailext subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - FAILED!!!',
                        body: '$DEFAULT_CONTENT',
                        recipientProviders: [
                            [$class: 'RequesterRecipientProvider']
                        ], 
                        replyTo: '$DEFAULT_REPLYTO',
                        to: 'prakash.mekapothula@cloud4c.com,satyanarayana.reddy@cloud4c.com,santosh.kalingwar@cloud4c.com,srija.yalala@cloud4c.com '
                        
                }
            }
            /*
            script {
                if (currentBuild.currentResult == 'SUCCESS') {
                   echo 'Running ADMIN-CENTER Selenium Testcases pipeline!'
                   build job: 'Selenium/OPF-ADMIN-functional-automation-scripts/', wait: false
                }
        }
        */

              updateGitlabCommitStatus(name: 'Jenkins', state: 'success')
              }
    }

  
}

