export const ActionTypes = {
    SET_THEME: "SET_THEME",
    SET_ENTITY: "SET_ENTITY",
    SET_TICKETS:"SET_TICKETS",
    SET_DATE_RANGE:"SET_DATE_RANGE",
    SET_STATUS_COUNT:"SET_STATUS_COUNT",
    SET_TICKET_FLAG:"SET_TICKET_FLAG",
    SET_UNASSIGN_FLAG:"SET_UNASSIGN_FLAG",
    SET_TILE_FLAG:"SET_TILE_FLAG",
    SET_CANVAS_FLAG:"SET_CANVAS_FLAG",
    SET_WORKFLOW_NAME:"SET_WORKFLOW_NAME",
    SET_TOOGLE_NOTIFICATION: "SET_TOOGLE_NOTIFICATION",
    SET_FALLBACK_ERRROR:"SET_FALLBACK_ERRROR",
    SET_IS_LOADING:"SET_IS_LOADING"
}