apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-five
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    #nginx.ingress.kubernetes.io/enable-cors: "true"
    


#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: ingress-resource-gateway
spec:
  tls:
  - hosts:
    - itsmgateway.cloud4c.com
    secretName: my-tls-key
  rules:
  - host: itsmgateway.cloud4c.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway-service
            port:
              number: 80
