apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ticket
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ticket
  targetCPUUtilizationPercentage: 70
