apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.labels }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.targetPort }}

