apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-five
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://itsm.cloud4c.com"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";



#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: ingress-resource-appmodernizationbackend
spec:
  tls:
  - hosts:
    - itsmnbe.cloud4c.com
    secretName: my-tls-key
  rules:
  - host: itsmnbe.cloud4c.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: appmodernizationbackend-service
            port:
              number: 80
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: appmodernizationbackend-service
            port:
              number: 80
