apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: appmodernization
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appmodernization
  targetCPUUtilizationPercentage: 70
